name: Update Readme

on:
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: |
          pip install requests
          python ./update.py

      - name: Commit
        run: |
          git config --global user.name showd0wn
          git config --global user.email showd0wn@163.com
          git add .
          git commit -m "docs: 更新进度"

      - name: Push
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
